SELECT ID
	  ,ISNULL([RAM], '0') [RAM]
	  ,ISNULL([SRI], '0') [SRI]
FROM [dbo].[Person]
PIVOT (SUM(SALARY) FOR NAME IN ([RAM], [SRI])) AS PVT

GO

SELECT *
FROM 
(
	SELECT ID
		  ,ISNULL([RAM], '0') [RAM]
		  ,ISNULL([SRI], '0') [SRI]
	FROM [dbo].[Person]
	PIVOT (SUM(SALARY) FOR NAME IN ([RAM], [SRI])) AS PVT
) T
UNPIVOT(SALARY FOR NAME IN ([RAM],[SRI])) AS UPVT
WHERE SALARY <> 0

GO

SELECT *
FROM [dbo].[Person]

ALTER TABLE [dbo].[Person]
ALTER COLUMN SALARY MONEY NOT NULL