ALTER TABLE [dbo].[Person]
ADD ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START CONSTRAINT DEF_ValidFrom DEFAULT SYSUTCDATETIME(),
	ValidTo  DATETIME2 GENERATED ALWAYS AS ROW END CONSTRAINT DEF_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31'),
	PERIOD FOR SYSTEM_TIME(ValidFrom, ValidTo)


ALTER TABLE [dbo].[Person]
ADD ValidFrom DATETIME2 CONSTRAINT DEF_ValidFrom DEFAULT GETDATE()

SELECT *
FROM [dbo].[Person]