CREATE SCHEMA MR 

GO

SELECT OBJECT_ID('[SQLPractice].[dbo].[Person]')

SELECT OBJECT_ID('MR.Employee')


CREATE TABLE [MR].[Employee]
(
	ID INT,
	NAME VARCHAR(50)
)


SELECT TRY_CONVERT(INT, 'lkadoi')
SELECT TRY_CONVERT(INT, '123')

BEGIN TRY 
	SELECT 1/0
END TRY
BEGIN CATCH
	RAISERROR ('New Fancy Error', 17, 1)
	SELECT @@ERROR
	SELECT ERROR_MESSAGE(), ERROR_NUMBER(), ERROR_LINE(), ERROR_SEVERITY(), ERROR_STATE();
	THROW 1234121, 'Fancy Error', 1
END CATCH

SELECT * FROM sys.objects

DECLARE @A INT
SET @A = 1

SELECT @@ROWCOUNT