"use strict";
exports.__esModule = true;
var name = "";
console.log(typeof (name) + " - " + name);
var count = 1000;
console.log(typeof (count) + " - " + count);
var floatNumber = 10.00010;
console.log(typeof (floatNumber) + " - " + floatNumber);
var decimalNumber = 0.00009093840982;
console.log(typeof (decimalNumber) + " - " + decimalNumber);
var isTypeScript = true;
console.log(typeof (isTypeScript) + " - " + isTypeScript);
var anyType = "";
console.log(typeof (anyType) + " - " + anyType);
var dynamicType;
dynamicType = "";
dynamicType = dynamicType.toUpperCase();
console.log(typeof (dynamicType) + " - " + dynamicType);
var binary = 170;
console.log(typeof (binary) + " - " + binary);
var hexaDecimal = 0x1ff0;
console.log(typeof (hexaDecimal) + " - " + hexaDecimal);
var octal = 484;
console.log(typeof (octal) + " - " + octal);
var arrayType = [1, 2, 3, 4];
console.log(typeof (arrayType) + " - " + arrayType);
var tupleType = ["Ram", 100, true];
console.log(typeof (tupleType) + " - " + tupleType);
var arbitaryType = " Cool ";
arbitaryType = arbitaryType.repeat(3);
console.log(arbitaryType);
